package fr.eisti.cergy.jee.model;
// Generated 19-Nov-2018 06:45:51 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours implements java.io.Serializable {

	private BigDecimal id;
	private String nom;
	private double moyenne;
	private Set<NoterCours> noterCourses = new HashSet<NoterCours>(0);

	public Cours() {
	}

	public Cours(BigDecimal id, String nom, double moyenne) {
		this.id = id;
		this.nom = nom;
		this.moyenne = moyenne;
	}

	public Cours(BigDecimal id, String nom, double moyenne, Set<NoterCours> noterCourses) {
		this.id = id;
		this.nom = nom;
		this.moyenne = moyenne;
		this.noterCourses = noterCourses;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public double getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(double moyenne) {
		this.moyenne = moyenne;
	}

	public Set<NoterCours> getNoterCourses() {
		return this.noterCourses;
	}

	public void setNoterCourses(Set<NoterCours> noterCourses) {
		this.noterCourses = noterCourses;
	}

}
