package fr.eisti.cergy.jee.model;
// Generated 19-Nov-2018 06:45:51 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Evenement generated by hbm2java
 */
public class Evenement implements java.io.Serializable {

	private BigDecimal id;
	private String nom;
	private double moyenne;
	private Set<NoterEvenement> noterEvenements = new HashSet<NoterEvenement>(0);

	public Evenement() {
	}

	public Evenement(BigDecimal id, String nom, double moyenne) {
		this.id = id;
		this.nom = nom;
		this.moyenne = moyenne;
	}

	public Evenement(BigDecimal id, String nom, double moyenne, Set<NoterEvenement> noterEvenements) {
		this.id = id;
		this.nom = nom;
		this.moyenne = moyenne;
		this.noterEvenements = noterEvenements;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public double getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(double moyenne) {
		this.moyenne = moyenne;
	}

	public Set<NoterEvenement> getNoterEvenements() {
		return this.noterEvenements;
	}

	public void setNoterEvenements(Set<NoterEvenement> noterEvenements) {
		this.noterEvenements = noterEvenements;
	}

}
