package fr.eisti.cergy.jee.model;
// Generated 19-Nov-2018 06:45:51 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * NoterAssociationId generated by hbm2java
 */
public class NoterAssociationId implements java.io.Serializable {

	private String mailUtilisateur;
	private BigDecimal idAssociation;

	public NoterAssociationId() {
	}

	public NoterAssociationId(String mailUtilisateur, BigDecimal idAssociation) {
		this.mailUtilisateur = mailUtilisateur;
		this.idAssociation = idAssociation;
	}

	public String getMailUtilisateur() {
		return this.mailUtilisateur;
	}

	public void setMailUtilisateur(String mailUtilisateur) {
		this.mailUtilisateur = mailUtilisateur;
	}

	public BigDecimal getIdAssociation() {
		return this.idAssociation;
	}

	public void setIdAssociation(BigDecimal idAssociation) {
		this.idAssociation = idAssociation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NoterAssociationId))
			return false;
		NoterAssociationId castOther = (NoterAssociationId) other;

		return ((this.getMailUtilisateur() == castOther.getMailUtilisateur())
				|| (this.getMailUtilisateur() != null && castOther.getMailUtilisateur() != null
						&& this.getMailUtilisateur().equals(castOther.getMailUtilisateur())))
				&& ((this.getIdAssociation() == castOther.getIdAssociation())
						|| (this.getIdAssociation() != null && castOther.getIdAssociation() != null
								&& this.getIdAssociation().equals(castOther.getIdAssociation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMailUtilisateur() == null ? 0 : this.getMailUtilisateur().hashCode());
		result = 37 * result + (getIdAssociation() == null ? 0 : this.getIdAssociation().hashCode());
		return result;
	}

}
