package fr.eisti.cergy.jee.model;
// Generated 19-Nov-2018 06:45:51 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * NoterEvenement generated by hbm2java
 */
public class NoterEvenement implements java.io.Serializable {

	private NoterEvenementId id;
	private Utilisateur utilisateur;
	private Evenement evenement;
	private BigDecimal note;

	public NoterEvenement() {
	}

	public NoterEvenement(NoterEvenementId id, Utilisateur utilisateur, Evenement evenement, BigDecimal note) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.evenement = evenement;
		this.note = note;
	}

	public NoterEvenementId getId() {
		return this.id;
	}

	public void setId(NoterEvenementId id) {
		this.id = id;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	public BigDecimal getNote() {
		return this.note;
	}

	public void setNote(BigDecimal note) {
		this.note = note;
	}

}
