package fr.eisti.cergy.jee.model;
// Generated 19-Nov-2018 06:45:51 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * NoterAssociation generated by hbm2java
 */
public class NoterAssociation implements java.io.Serializable {

	private NoterAssociationId id;
	private Utilisateur utilisateur;
	private Association association;
	private BigDecimal note;

	public NoterAssociation() {
	}

	public NoterAssociation(NoterAssociationId id, Utilisateur utilisateur, Association association, BigDecimal note) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.association = association;
		this.note = note;
	}

	public NoterAssociationId getId() {
		return this.id;
	}

	public void setId(NoterAssociationId id) {
		this.id = id;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Association getAssociation() {
		return this.association;
	}

	public void setAssociation(Association association) {
		this.association = association;
	}

	public BigDecimal getNote() {
		return this.note;
	}

	public void setNote(BigDecimal note) {
		this.note = note;
	}

}
